baseURL = "http://wtysos11.github.io/"
title = "实践出真知"
theme = "hugo-coder"
languagecode = "zh"
defaultcontentlanguage = "zh"

[markup.highlight]
style = "github-dark"

[params]
  author = "Timothy Wu"
  info = "中山大学软件工程本硕，目前为腾讯WXG数据开发。博客内容主要包括对后台开发知识的学习，以及对其他内容的思考"
  description = "challenge yourself, and make a difference"
  keywords = "blog,developer,personal"


  since = 2020

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/wtysos11/"
[[params.social]]
  name = "blog"
  icon = "fa-brands fa-wordpress fa-2x"
  weight = 2
  url = "https://cloud.tencent.com/developer/column/95827"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"
[[menu.main]]
  name = "Categories"
  weight = 3
  url = "categories/"
[[menu.main]]
  name = "series"
  weight = 4
  url = "series/"
